import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloWrapper } from "@/lib/apolloWrapper";
import Header from "@/components/Header";
import AppContextProvider from "@/components/AppContext";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <Script
          src='//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js'
          // strategy='lazyOnload'
          strategy='afterInteractive'
          defer
        />
        <AppContextProvider>
          <Header />
          <ApolloWrapper>{children}</ApolloWrapper>
        </AppContextProvider>
      </body>
    </html>
  );
}
