import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ApolloWrapper } from "@/lib/apolloWrapper";
import Header from "@/components/Header";
import AppContextProvider from "@/components/AppContext";
import Footer from "@/components/Footer";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getSorryData() {
  const res = await fetch("https://api.sorryapp.com/v1/pages/9f57a5cb/notices");
  // The return value is *not* serialized
  // You can return Date, Map, Set, etc.

  if (!res.ok) {
    // This will activate the closest `error.js` Error Boundary
    throw new Error("Failed to fetch data");
  }

  return res.json();
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const sorryData = await getSorryData();

  return (
    <html lang='en'>
      <body className={`${inter.className}`}>
        <Script
          src='//widget.trustpilot.com/bootstrap/v5/tp.widget.bootstrap.min.js'
          // strategy='lazyOnload'
          strategy='afterInteractive'
          defer
        />
        <AppContextProvider>
          <Header sorryData={sorryData} />
          <ApolloWrapper>{children}</ApolloWrapper>
          <Footer />
        </AppContextProvider>
      </body>
    </html>
  );
}
